# INFO: VSCodeの置換を使って ./lib 内の base_sample のimportを一括変更し、ここの name も変更する
name: objectbox_sample
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: 1.0.8
  derry: 1.5.0
  flutter:
    sdk: flutter
  flutter_hooks: 0.21.3+1
  hooks_riverpod: 3.0.3
  riverpod_annotation: 3.0.3
  gap: 3.0.1
  logger: 2.6.2
  very_good_analysis: 10.0.0
  # INFO: 個人作成のWidgetパッケージ -> 未使用であれば削除
  utility_widgets:
    git:
      url: https://github.com/HaruhikoMotokawa/utility_widgets.git
      ref: v1.0.0
  freezed_annotation: 3.1.0
  json_annotation: 4.9.0
  rename_app: 1.6.5
  go_router: 17.0.0
  objectbox: 5.0.4

dev_dependencies:
  build_runner: 2.7.1
  riverpod_generator: 3.0.3
  riverpod_lint: 3.0.3
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  freezed: 3.2.3
  json_serializable: 6.11.2
  flutter_localizations:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true

scripts:
  # build_runnerを実行して、同じファイル名があれば古いものを削除する
  build: dart run build_runner build -d
  # 保存するたびにbuild_runnerを実行して変更を走らせるようになる
  watch: fvm dart run build_runner watch -d
  #  Gradle デーモンプロセスを終了する => ビルドエラーの解消
  gc: pkill -f '.*GradleDaemon.*'
  # テストを実行しカバレッジをHTMLで出力してブラウザで開くスクリプト
  cov: flutter test --coverage && lcov --remove coverage/lcov.info 'lib/**.g.dart' -o coverage/new_lcov.info --ignore-errors unused && genhtml coverage/new_lcov.info -o coverage/html && open coverage/html/index.html
  # very_good testバージョン -> 最初にdart pub global activate very_good_cliで設定が必要
  cov_good: very_good test -- --coverage && lcov --remove coverage/lcov.info 'lib/**.g.dart' -o coverage/lcov.info && genhtml coverage/lcov.info -o coverage/html && open coverage/html/index.html
  # flutterのパッケージとパッケージのキャッシュを削除した上で、再度パッケージを取得する
  reset_flutter: flutter clean && flutter pub cache repair && flutter pub get --no-example
  # 初期設定のスクリプト
  # INFO:実行する前にVScodeの置換機能を使ってConstants.appNameとこのスクリプト内の [ ObjectboxSample ]を任意の名前に変えておく
  init_app: rm -rf .git && git init && dart run build_runner build --delete-conflicting-outputs && dart run rename_app:main all="ObjectboxSample"
